
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import AST.*;
import java_cup.runtime.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\046\000\002\002\005\000\002\002\004\000\002\003" +
    "\006\000\002\003\002\000\002\017\004\000\002\017\002" +
    "\000\002\020\006\000\002\020\007\000\002\004\004\000" +
    "\002\004\002\000\002\005\007\000\002\005\007\000\002" +
    "\005\004\000\002\006\004\000\002\006\003\000\002\007" +
    "\007\000\002\010\004\000\002\010\003\000\002\011\003" +
    "\000\002\011\003\000\002\012\005\000\002\012\005\000" +
    "\002\012\010\000\002\012\010\000\002\012\005\000\002" +
    "\012\005\000\002\013\004\000\002\013\002\000\002\014" +
    "\007\000\002\015\006\000\002\015\006\000\002\015\002" +
    "\000\002\016\007\000\002\016\007\000\002\016\011\000" +
    "\002\016\010\000\002\016\010\000\002\016\007" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\140\000\010\007\004\012\ufffe\013\ufffe\001\002\000" +
    "\004\024\126\001\002\000\004\002\125\001\002\000\006" +
    "\012\ufff8\013\ufff8\001\002\000\006\012\010\013\012\001" +
    "\002\000\006\003\116\004\117\001\002\000\006\012\ufff9" +
    "\013\ufff9\001\002\000\004\004\016\001\002\000\006\002" +
    "\ufff3\013\ufff3\001\002\000\006\002\001\013\012\001\002" +
    "\000\006\002\ufff4\013\ufff4\001\002\000\004\024\017\001" +
    "\002\000\014\014\027\015\026\016\020\017\024\020\022" +
    "\001\002\000\004\005\110\001\002\000\016\014\uffef\015" +
    "\uffef\016\uffef\017\uffef\020\uffef\025\uffef\001\002\000\010" +
    "\011\063\021\061\022\062\001\002\000\016\014\027\015" +
    "\026\016\020\017\024\020\022\025\060\001\002\000\004" +
    "\005\055\001\002\000\016\014\ufff0\015\ufff0\016\ufff0\017" +
    "\ufff0\020\ufff0\025\ufff0\001\002\000\004\005\033\001\002" +
    "\000\004\005\031\001\002\000\016\014\uffee\015\uffee\016" +
    "\uffee\017\uffee\020\uffee\025\uffee\001\002\000\004\026\032" +
    "\001\002\000\016\014\uffed\015\uffed\016\uffed\017\uffed\020" +
    "\uffed\025\uffed\001\002\000\006\024\034\026\035\001\002" +
    "\000\010\011\uffe6\022\uffe6\025\uffe6\001\002\000\016\014" +
    "\uffe9\015\uffe9\016\uffe9\017\uffe9\020\uffe9\025\uffe9\001\002" +
    "\000\010\011\041\022\040\025\uffe2\001\002\000\004\025" +
    "\054\001\002\000\004\027\047\001\002\000\004\005\043" +
    "\001\002\000\010\011\uffe7\022\uffe7\025\uffe7\001\002\000" +
    "\004\027\044\001\002\000\004\005\045\001\002\000\004" +
    "\026\046\001\002\000\010\011\uffe5\022\uffe5\025\uffe5\001" +
    "\002\000\006\005\050\006\051\001\002\000\004\026\053" +
    "\001\002\000\004\026\052\001\002\000\004\025\uffe3\001" +
    "\002\000\004\025\uffe4\001\002\000\016\014\uffeb\015\uffeb" +
    "\016\uffeb\017\uffeb\020\uffeb\025\uffeb\001\002\000\004\026" +
    "\056\001\002\000\016\014\uffec\015\uffec\016\uffec\017\uffec" +
    "\020\uffec\025\uffec\001\002\000\016\014\ufff1\015\ufff1\016" +
    "\ufff1\017\ufff1\020\ufff1\025\ufff1\001\002\000\006\002\ufff2" +
    "\013\ufff2\001\002\000\006\027\077\030\076\001\002\000" +
    "\004\023\073\001\002\000\004\005\064\001\002\000\006" +
    "\023\065\027\066\001\002\000\004\005\071\001\002\000" +
    "\004\005\067\001\002\000\004\026\070\001\002\000\016" +
    "\014\uffde\015\uffde\016\uffde\017\uffde\020\uffde\025\uffde\001" +
    "\002\000\004\026\072\001\002\000\016\014\uffdd\015\uffdd" +
    "\016\uffdd\017\uffdd\020\uffdd\025\uffdd\001\002\000\004\005" +
    "\074\001\002\000\004\026\075\001\002\000\016\014\uffdc" +
    "\015\uffdc\016\uffdc\017\uffdc\020\uffdc\025\uffdc\001\002\000" +
    "\004\006\104\001\002\000\006\005\100\006\101\001\002" +
    "\000\004\026\103\001\002\000\004\026\102\001\002\000" +
    "\016\014\uffe1\015\uffe1\016\uffe1\017\uffe1\020\uffe1\025\uffe1" +
    "\001\002\000\016\014\uffe0\015\uffe0\016\uffe0\017\uffe0\020" +
    "\uffe0\025\uffe0\001\002\000\004\031\105\001\002\000\004" +
    "\006\106\001\002\000\004\026\107\001\002\000\016\014" +
    "\uffdf\015\uffdf\016\uffdf\017\uffdf\020\uffdf\025\uffdf\001\002" +
    "\000\006\024\111\026\112\001\002\000\010\011\uffe6\022" +
    "\uffe6\025\uffe6\001\002\000\016\014\uffe8\015\uffe8\016\uffe8" +
    "\017\uffe8\020\uffe8\025\uffe8\001\002\000\010\011\041\022" +
    "\040\025\uffe2\001\002\000\004\025\115\001\002\000\016" +
    "\014\uffea\015\uffea\016\uffea\017\uffea\020\uffea\025\uffea\001" +
    "\002\000\006\012\ufff5\013\ufff5\001\002\000\004\027\120" +
    "\001\002\000\006\005\121\006\122\001\002\000\004\026" +
    "\124\001\002\000\004\026\123\001\002\000\006\012\ufff6" +
    "\013\ufff6\001\002\000\006\012\ufff7\013\ufff7\001\002\000" +
    "\004\002\000\001\002\000\010\010\ufffc\011\ufffc\025\ufffc" +
    "\001\002\000\010\010\133\011\132\025\131\001\002\000" +
    "\010\010\ufffd\011\ufffd\025\ufffd\001\002\000\006\012\uffff" +
    "\013\uffff\001\002\000\004\005\137\001\002\000\004\027" +
    "\134\001\002\000\004\005\135\001\002\000\004\026\136" +
    "\001\002\000\010\010\ufffb\011\ufffb\025\ufffb\001\002\000" +
    "\004\027\140\001\002\000\004\005\141\001\002\000\004" +
    "\026\142\001\002\000\010\010\ufffa\011\ufffa\025\ufffa\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\140\000\006\002\004\003\005\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\004\006\001\001\000\010" +
    "\005\010\006\013\007\012\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\007\014\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\010\022\011\024\012\020\016\027\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\011" +
    "\056\012\020\016\027\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\013\035\001\001\000\002\001\001\000\006\014" +
    "\041\015\036\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\013\112\001\001\000\002\001" +
    "\001\000\006\014\041\015\113\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\017" +
    "\126\001\001\000\004\020\127\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private int errorCount = 0;

    public void syntax_error(Symbol cur_token) {
        errorCount++;
        report_error("Syntax error at line " + (cur_token.left + 1), null);
    }

    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        errorCount++;
        report_fatal_error("Fatal syntax error at line " + (cur_token.left + 1), null);
    }

    public void report_error(String message, Object info) {
        System.err.println(message);
    }

    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
        report_error(message, info);
        throw new Exception("Parse failed due to syntax errors");
    }

    public boolean hasErrors() {
        return errorCount > 0;
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= config_block let_stmts test_blocks 
            {
              Program RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ConfigBlock c = (ConfigBlock)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<LetStmt> l = (List<LetStmt>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		List<TestBlock> t = (List<TestBlock>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
       Set<String> names = new HashSet<>();
       for (LetStmt let : l) {
           if (!names.add(let.name)) {
               throw new RuntimeException("Duplicate variable '" + let.name + "'");
           }
       }
       RESULT = new Program(c, l, t);
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // config_block ::= CONFIG LBRACE config_items RBRACE 
            {
              ConfigBlock RESULT =null;
		int itemsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int itemsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<ConfigItem> items = (List<ConfigItem>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new ConfigBlock(items); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_block",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // config_block ::= 
            {
              ConfigBlock RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_block",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // config_items ::= config_items config_item 
            {
              List<ConfigItem> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<ConfigItem> list = (List<ConfigItem>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int itemleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int itemright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ConfigItem item = (ConfigItem)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 list.add(item); RESULT=list; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_items",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // config_items ::= 
            {
              List<ConfigItem> RESULT =null;
		 RESULT = new ArrayList<ConfigItem>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_items",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // config_item ::= BASE_URL EQUALS STRING SEMI 
            {
              ConfigItem RESULT =null;
		int urlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int urlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String url = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new ConfigItem("base_url", url); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_item",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // config_item ::= HEADER STRING EQUALS STRING SEMI 
            {
              ConfigItem RESULT =null;
		int keyleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int keyright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String key = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new ConfigItem("header", key, val); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("config_item",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // let_stmts ::= let_stmts let_stmt 
            {
              List<LetStmt> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<LetStmt> list = (List<LetStmt>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		LetStmt stmt = (LetStmt)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 list.add(stmt); RESULT=list; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("let_stmts",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // let_stmts ::= 
            {
              List<LetStmt> RESULT =null;
		 RESULT = new ArrayList<LetStmt>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("let_stmts",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // let_stmt ::= LET IDENT EQUALS STRING SEMI 
            {
              LetStmt RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new LetStmt(name, val, false, nameleft); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("let_stmt",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // let_stmt ::= LET IDENT EQUALS NUMBER SEMI 
            {
              LetStmt RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new LetStmt(name, val, true, nameleft); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("let_stmt",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // let_stmt ::= LET error 
            {
              LetStmt RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
        System.err.println("Identifier cannot start with a digit");
        System.err.println("Line " + (eleft + 1) + ": expected IDENT after 'let'");
        parser.report_fatal_error("", null);
        RESULT = null;
    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("let_stmt",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // test_blocks ::= test_blocks test_block 
            {
              List<TestBlock> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<TestBlock> list = (List<TestBlock>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int blockleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int blockright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		TestBlock block = (TestBlock)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 list.add(block); RESULT=list; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("test_blocks",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // test_blocks ::= test_block 
            {
              List<TestBlock> RESULT =null;
		int blockleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int blockright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		TestBlock block = (TestBlock)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 List<TestBlock> list = new ArrayList<>(); list.add(block); RESULT=list; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("test_blocks",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // test_block ::= TEST IDENT LBRACE statements RBRACE 
            {
              TestBlock RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int stmtsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int stmtsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<Statement> stmts = (List<Statement>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new TestBlock(name, stmts); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("test_block",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // statements ::= statements statement 
            {
              List<Statement> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<Statement> list = (List<Statement>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Statement stmt = (Statement)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 list.add(stmt); RESULT=list; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statements",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // statements ::= statement 
            {
              List<Statement> RESULT =null;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Statement stmt = (Statement)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 List<Statement> list = new ArrayList<>(); list.add(stmt); RESULT=list; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statements",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // statement ::= request_stmt 
            {
              Statement RESULT =null;
		int reqleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int reqright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		RequestStmt req = (RequestStmt)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT=req; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // statement ::= assertion 
            {
              Statement RESULT =null;
		int astleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int astright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		AssertStmt ast = (AssertStmt)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT=ast; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // request_stmt ::= GET STRING SEMI 
            {
              RequestStmt RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT=new RequestStmt("GET", path, new ArrayList<>(), null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("request_stmt",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // request_stmt ::= DELETE STRING SEMI 
            {
              RequestStmt RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT=new RequestStmt("DELETE", path, new ArrayList<>(), null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("request_stmt",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // request_stmt ::= POST STRING LBRACE header_stmts body_stmt RBRACE 
            {
              RequestStmt RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int headersleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int headersright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<HeaderStmt> headers = (List<HeaderStmt>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		BodyStmt body = (BodyStmt)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT=new RequestStmt("POST", path, headers, body); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("request_stmt",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // request_stmt ::= PUT STRING LBRACE header_stmts body_stmt RBRACE 
            {
              RequestStmt RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int headersleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int headersright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		List<HeaderStmt> headers = (List<HeaderStmt>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		BodyStmt body = (BodyStmt)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT=new RequestStmt("PUT", path, headers, body); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("request_stmt",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // request_stmt ::= POST STRING SEMI 
            {
              RequestStmt RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT=new RequestStmt("POST", path, new ArrayList<>(), null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("request_stmt",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // request_stmt ::= PUT STRING SEMI 
            {
              RequestStmt RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT=new RequestStmt("PUT", path, new ArrayList<>(), null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("request_stmt",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // header_stmts ::= header_stmts header_stmt 
            {
              List<HeaderStmt> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		List<HeaderStmt> list = (List<HeaderStmt>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int stmtleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int stmtright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		HeaderStmt stmt = (HeaderStmt)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 list.add(stmt); RESULT=list; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("header_stmts",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // header_stmts ::= 
            {
              List<HeaderStmt> RESULT =null;
		 RESULT=new ArrayList<HeaderStmt>(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("header_stmts",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // header_stmt ::= HEADER STRING EQUALS STRING SEMI 
            {
              HeaderStmt RESULT =null;
		int keyleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int keyright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String key = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT=new HeaderStmt(key, val); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("header_stmt",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // body_stmt ::= BODY EQUALS STRING SEMI 
            {
              BodyStmt RESULT =null;
		int contentleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int contentright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String content = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT=new BodyStmt(content); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("body_stmt",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // body_stmt ::= BODY EQUALS NUMBER SEMI 
            {
              BodyStmt RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int numright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String num = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
            System.err.println("Body must be a string");
            System.err.println("Line " + (numleft + 1) + ": expected STRING after 'body ='");
            parser.report_fatal_error("", null);
            RESULT = null;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("body_stmt",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // body_stmt ::= 
            {
              BodyStmt RESULT =null;
		 RESULT=null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("body_stmt",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // assertion ::= EXPECT STATUS EQUALS NUMBER SEMI 
            {
              AssertStmt RESULT =null;
		int codeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int coderight = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String code = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT=new AssertStmt("status", null, code, false); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assertion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // assertion ::= EXPECT STATUS EQUALS STRING SEMI 
            {
              AssertStmt RESULT =null;
		int codeleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int coderight = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String code = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
            System.err.println("Status must be integer");
            System.err.println("Line " + (codeleft + 1) + ": expected NUMBER for status, got \"" + code + "\"");
            parser.report_fatal_error("", null);
            RESULT = null;
        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assertion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // assertion ::= EXPECT STATUS IN NUMBER DOTDOT NUMBER SEMI 
            {
              AssertStmt RESULT =null;
		int startleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int startright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String start = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int endleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int endright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String end = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT=new AssertStmt("status_range", null, start + ".." + end, false); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assertion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // assertion ::= EXPECT HEADER STRING EQUALS STRING SEMI 
            {
              AssertStmt RESULT =null;
		int keyleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int keyright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String key = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT=new AssertStmt("header", key, val, false); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assertion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // assertion ::= EXPECT HEADER STRING CONTAINS STRING SEMI 
            {
              AssertStmt RESULT =null;
		int keyleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int keyright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String key = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT=new AssertStmt("header", key, val, true); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assertion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // assertion ::= EXPECT BODY CONTAINS STRING SEMI 
            {
              AssertStmt RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT=new AssertStmt("body", null, val, true); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("assertion",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
