
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POST = 11;
  public static final int IDENT = 2;
  public static final int RBRACE = 19;
  public static final int TEST = 9;
  public static final int SEMI = 20;
  public static final int STATUS = 15;
  public static final int EXPECT = 14;
  public static final int LBRACE = 18;
  public static final int PUT = 12;
  public static final int CONTAINS = 17;
  public static final int EQUALS = 21;
  public static final int STRING = 3;
  public static final int EOF = 0;
  public static final int NUMBER = 4;
  public static final int error = 1;
  public static final int LET = 8;
  public static final int BODY = 16;
  public static final int HEADER = 7;
  public static final int BASE_URL = 6;
  public static final int DELETE = 13;
  public static final int CONFIG = 5;
  public static final int GET = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENT",
  "STRING",
  "NUMBER",
  "CONFIG",
  "BASE_URL",
  "HEADER",
  "LET",
  "TEST",
  "GET",
  "POST",
  "PUT",
  "DELETE",
  "EXPECT",
  "STATUS",
  "BODY",
  "CONTAINS",
  "LBRACE",
  "RBRACE",
  "SEMI",
  "EQUALS"
  };
}

